spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: auth-service
      auto-offset-reset: earliest
  redis:

jwt:
  access:
    expiration: 900_000
  refresh:
    expiration: 604_800_000